name: Build Ren’Py iOS App test 2

# Define when the workflow runs
on:
  workflow_dispatch:
    branches:
      - main

# Define the jobs
jobs:
  build:
    # Use the latest macOS runner for Xcode compatibility
    runs-on: macos-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      # Step 2: Download Ren’Py SDK version 8.3.7
      - name: Download Ren’Py SDK
        run: |
          curl -O https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
          unzip renpy-8.3.7-sdk.zip
        # Downloads and extracts the SDK from the official Ren’Py site

      # Step 3: Make the renpy.sh script executable
      - name: Make renpy.sh executable
        run: |
          chmod +x renpy-8.3.7-sdk/renpy.sh
        # Ensures the Ren’Py script can be executed

      # Step 4: Clone rapt, renios, and renpyweb libraries
      - name: Clone rapt, renios, renpyweb
        run: |
          git clone https://${{ secrets.RENPY_BUILD_TOKEN }}@github.com/renpy/rapt.git renpy-8.3.7-sdk/rapt
          git clone https://${{ secrets.RENPY_BUILD_TOKEN }}@github.com/renpy/renios.git renpy-8.3.7-sdk/renios
          git clone https://${{ secrets.RENPY_BUILD_TOKEN }}@github.com/renpy/renpyweb.git renpy-8.3.7-sdk/renpyweb
        # Clones the required libraries into the SDK directory using the token for authentication

      # Step 5: Generate the iOS distribution
      - name: Build iOS distribution
        run: |
          cd renpy-8.3.7-sdk
          ./launcher ../ distribute --package ios
          cd ..
        # Runs the Ren’Py distribute command to generate an iOS Xcode project
        # '../' refers to the repository root where the project is checked out

      # Step 6: Build the Xcode project
      - name: Build Xcode project
        run: |
          xcodebuild -project dists/Cockham_Superheroes-ios/Cockham_Superheroes.xcodeproj -scheme Cockham_Superheroes -configuration Release
        # Builds the generated Xcode project; paths and scheme names are assumed based on project naming