name: Build Ren'Py iOS

# Trigger the workflow on push events
on: [push]

jobs:
  build:
    # Use a macOS runner since Xcode is required for iOS builds
    runs-on: macos-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Ren'Py with version 8.3.7
      - name: Setup Ren'Py
        uses: renpy/setup-renpy@v1
        with:
          version: '8.3.7'          # Specifies Ren'Py SDK version 8.3.7
          update_path: true         # Adds Ren'Py to the PATH

      # Step 3: Generate the iOS project with Ren'Py
      - name: Build Ren'Py iOS project
        run: renpy.sh . distribute --package ios

      # Step 4: Build the Xcode project without signing
      - name: Build Xcode project
        run: |
          xcodebuild -project build/ios/Cockham_Superheroes.xcodeproj \
                     -scheme Cockham_Superheroes \
                     -configuration Release \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO

      # Step 5: Upload the build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Cockham_Superheroes_ios_build
          path: build/ios/build/Release-iphoneos/Cockham_Superheroes.app