name: Build Ren'Py iOS App test 5

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download Ren'Py SDK
      run: |
        curl -o renpy-sdk.zip https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
        unzip renpy-sdk.zip -d renpy

    - name: Download and install rapt
      run: |
        curl -o rapt.zip https://www.renpy.org/dl/8.3.7/renpy-8.3.7-rapt.zip
        unzip rapt.zip -d renpy/renpy-8.3.7-sdk

    - name: Download and install renios
      run: |
        curl -o renios.zip https://www.renpy.org/dl/8.3.7/renpy-8.3.7-renios.zip
        unzip renios.zip -d renpy/renpy-8.3.7-sdk

    - name: Download and install renpyweb
      run: |
        curl -o renpyweb.zip https://www.renpy.org/dl/8.3.7/renpy-8.3.7-web.zip
        unzip renpyweb.zip -d renpy/renpy-8.3.7-sdk
    - name: Build for iOS 
      run: |
        cd renpy/renpy-8.3.7-sdk
        ./renpy.sh launcher ios_create $GITHUB_WORKSPACE ios
        ./renpy.sh launcher ios_populate $GITHUB_WORKSPACE ios
 
      # Upload the IPA file as a release asset
    - name: Create Release
      uses: ncipollo/release-action@v1.16.0
      with:
        artifacts: "*.ipa"
