name: Build Ren'Py iOS App test 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checkout the Cockham_Superheroes repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Download and set up Ren'Py SDK version 8.3.7
      - name: Download Ren'Py SDK
        run: |
          curl -O https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
          unzip renpy-8.3.7-sdk.zip -d renpy

      # Download and install renios for iOS support
      - name: Download renios
        run: |
          curl -O https://www.renpy.org/dl/8.3.7/renpy-8.3.7-renios.zip
          unzip renpy-8.3.7-renios.zip -d renpy/renios

      # Download and install rapt for Android support (included as requested)
      - name: Download rapt
        run: |
          curl -O https://www.renpy.org/dl/8.3.7/renpy-8.3.7-rapt.zip
          unzip renpy-8.3.7-rapt.zip -d renpy/rapt

      # Download and install renpyweb for web support (included as requested)
      - name: Download renpyweb
        run: |
          curl -O https://www.renpy.org/dl/8.3.7/renpy-8.3.7-web.zip
          unzip renpy-8.3.7-web.zip -d renpy/renpyweb

      # Generate the Xcode project for the iOS build
      - name: Generate Xcode project
        run: |
          cd renpy/renpy-8.3.7-sdk
          ./renpy.sh ../. ios create_project --dest ../ios-project

      # Create an ExportOptions.plist file for IPA export
      - name: Create ExportOptions.plist
        run: |
          cat > ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
          </dict>
          </plist>
          EOF

      # Build and archive the Xcode project
      - name: Build Xcode project
        run: |
          cd ios-project
          xcodebuild -scheme "Cockham Superheroes" -archivePath ./build/CockhamSuperheroes.xcarchive -sdk iphoneos -configuration Release clean archive

      # Export the archived project to an IPA file
      - name: Export IPA
        run: |
          cd ios-project
          xcodebuild -exportArchive -archivePath ./build/CockhamSuperheroes.xcarchive -exportOptionsPlist ../ExportOptions.plist -exportPath ./build

      # Create a GitHub release using the provided access token
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      # Upload the IPA file as a release asset
      - name: Upload IPA to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ios-project/build/CockhamSuperheroes.ipa
          asset_name: CockhamSuperheroes.ipa
          asset_content_type: application/octet-stream