  name: Build Ren'Py iOS App test 6

on: 
  push:
    branches:
      - main
jobs:
   build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository with PAT
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
    - name: Set Git configuration
      run: |
        git config user.name "CraZyP"
        git config user.email "crazyp@icloud.com"
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download Ren'Py SDK
      run: |
        curl -o renpy-sdk.zip https://www.renpy.org/dl/8.3.7/renpy-8.3.7-sdk.zip
        unzip renpy-sdk.zip -d renpy

    - name: Download and install rapt
      run: |
        curl -o rapt.zip https://www.renpy.org/dl/8.3.7/renpy-8.3.7-rapt.zip
        unzip rapt.zip -d renpy/renpy-8.3.7-sdk

    - name: Download and install renios
      run: |
        curl -o renios.zip https://www.renpy.org/dl/8.3.7/renpy-8.3.7-renios.zip
        unzip renios.zip -d renpy/renpy-8.3.7-sdk

    - name: Download and install renpyweb
      run: |
        curl -o renpyweb.zip https://www.renpy.org/dl/8.3.7/renpy-8.3.7-web.zip
        unzip renpyweb.zip -d renpy/renpy-8.3.7-sdk
    - name: Build for iOS 
      run: |
        cd renpy/renpy-8.3.7-sdk
        ./renpy.sh launcher ios_create $GITHUB_WORKSPACE ios
        ./renpy.sh launcher ios_populate $GITHUB_WORKSPACE ios
  
      # Upload the IPA file as a release asset
    - name: Create application Bundle and convert to .ipa 
      run: |
        mkdir Payload \;
        find / -maxdepth 1 -type d -name "renpy.app" -exec mv {} "Cockham Superheros.app" Payload/ \; 
        zip -r "Cockham Superheros.ipa" Payload \;
        rm -rf Payload \;

     - name: Create release and upload asset
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          shopt -s globstar
          gh release create ${{ github.ref_name }} **/Cockham_Superheros.zip --title "Release ${{ github.ref_name }}" --notes "Automated release"